### ISSUE TITLE
Project name does not match with name on packagist.org

### ISSUE THREAD

**Issue by stucki** [FriendsOfTYPO3/func#2]
The package name in `composer.json` is different to the name at https://packagist.org/packages/friendsoftypo3/cms-func.

```diff
-	"name": "friendsoftypo3/func",
+	"name": "friendsoftypo3/cms-func",
```

**Comment by ohader** [comment]
That has been introduced in bea537f7c0a09861b5dc3780d553860c1bdc80ee - unfortunately, I don't know why...

**Comment by stucki** [comment]
Thanks @ohader. I see that it was changed, however it's still wrong if not changed on both sides. Do you see any other extension where the package name is not the same?

In any case, it should be fixed. The commit should be reverted.

**Comment by bmack** [comment]
@stucki seems this is wrong (and was never actually published / released since then, I guess). Can you do a PR and fix it ? `friendsoftypo3/cms-func` seems to be the way to go IMHO.

**Comment by helhum** [comment]
> was never actually published / released since then, I guess

actually this change was tagged in v9.0.1. Not sure why Packagist did not pick up the new name though. Usually it does.

> Can you do a PR and fix it ?

Anyway, unfortunately this then also needs a new release in TER and a change in the TYPO3 upgrade wizard, that references the broken 9.0.1 release.

**Comment by stucki** [comment]
Ok I added the PR now. @bmack FYI.

**Comment by stucki** [comment]
@bmack Many thanks Benni!

> Anyway, unfortunately this then also needs a new release in TER and a change in the TYPO3 upgrade wizard, that references the broken 9.0.1 release.

@helhum Why does it? The name is only used by composer. In TER, the name was always `func` and remains unchanged.
