### ISSUE TITLE
TER release 9.0.1 not compatible with TYPO3 v9.5

### ISSUE THREAD

**Issue by cweiske** [FriendsOfTYPO3/func#5]
In TER, the currently available version is 9.0.1: https://extensions.typo3.org/extension/func

It is marked as compatible with "TYPO3 (9.0.0 - 9.0.99)".

The git version is marked as compatible with 9.5.99 (bb1035fa520efc619412fc78c94d1fc68a5d1bda), so there should be a TER release of func 9.0.2.

**Comment by ohader** [comment]
✅ done
→ https://extensions.typo3.org/extension/func
