### ISSUE TITLE
Missing TER version 9.0.2

### ISSUE THREAD

**Issue by ohader** [FriendsOfTYPO3/func#7]
* available on packagist https://packagist.org/packages/friendsoftypo3/cms-func
* missing in TER https://extensions.typo3.org/extension/func

→ upload new version 9.0.2 (based on corresponding Git tag) to extensions.typo3.org
Once this is done, TER composer reference can be switched from `friendsoftypo3/func` → to `friendsoftypo3/cms-func`

**Comment by alexander-nitsche** [comment]
Fixes: #5

**Comment by ohader** [comment]
✅ done
→ https://extensions.typo3.org/extension/func
